# Generated by Django 3.1.3 on 2021-02-10 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=11)),
                ('restaurant', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('food', models.IntegerField(null=True)),
                ('service', models.IntegerField(null=True)),
                ('value', models.IntegerField(null=True)),
                ('ambience', models.IntegerField(null=True)),
                ('text', models.TextField(max_length=10000)),
                ('replied', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=1000)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rep_app.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
