# Generated by Django 3.1.3 on 2021-02-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_app', '0003_auto_20210210_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
