# Generated by Django 3.1.3 on 2021-02-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_app', '0004_auto_20210211_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
