# Generated by Django 3.1.3 on 2021-03-10 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rep_app', '0007_auto_20210215_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='manager',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='review',
            name='link',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rep_app.manager')),
                ('ops_director', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rep_app.opsdirector')),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rep_app.restaurant'),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rep_app.restaurant'),
        ),
    ]
