# Generated by Django 3.1.3 on 2021-03-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rep_app', '0008_auto_20210310_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='manager',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='manager',
            field=models.ManyToManyField(null=True, to='rep_app.Manager'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='ops_director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rep_app.opsdirector'),
        ),
    ]
