# Generated by Django 3.1.3 on 2021-03-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rep_app', '0012_auto_20210312_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rep_app.restaurant'),
        ),
    ]
