# Generated by Django 3.1.3 on 2021-03-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rep_app', '0014_auto_20210323_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='tag',
            new_name='tags',
        ),
    ]
