# Generated by Django 3.1.3 on 2021-03-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_app', '0015_auto_20210323_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='display_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
