restaurant_list = {
    '100 Wardour Street': 1,
    '14 Hills': 2,
    '20 Stories': 3,
    'Angelica': 4,
    'Angler': 5,
    'Aster': 6,
    'Avenue': 7,
    'Bluebird Chelsea': 8,
    'Bluebird White City': 9,
    'Blueprint Café': 10,
    'Butlers Wharf Chophouse': 11,
    'Cantina': 12,
    "Coq d'Argent": 13,
    'Crafthouse': 14,
    'East 59th': 15,
    'Fish Market': 16,
    'Fiume': 17,
    'German Gymnasium': 18,
    'Issho': 19,
    'Klosterhaus': 20,
    'Launceston Place': 21,
    'Le Pont de la Tour': 22,
    'Madison': 23,
    'New Street Grill': 24,
    'New Street Wine': 25,
    'Old Bengal Bar': 26,
    'Orrery': 27,
    'Paternoster Chophouse': 28,
    'Plateau': 29,
    "Quaglino's": 30,
    'Radici': 31,
    'Sartoria': 32,
    'Skylon': 33,
    'South Place Chophouse': 34,
    'The Modern Pantry': 35
}