restaurant_list = [
    '100 Wardour Street',
    '14 Hills',
    '20 Stories',
    'Angelica',
    'Angler',
    'Aster',
    'Avenue',
    'Bluebird Chelsea',
    'Bluebird White City',
    'Blueprint Café',
    'Butlers Wharf Chophouse',
    'Cantina',
    "Coq d'Argent",
    'Crafthouse',
    'East 59th',
    'Fish Market',
    'Fiume',
    'German Gymnasium',
    'Issho',
    'Klosterhaus',
    'Launceston Place',
    'Le Pont de la Tour',
    'Madison',
    'New Street Grill',
    'New Street Wine',
    'Old Bengal Bar',
    'Orrery',
    'Paternoster Chophouse',
    'Plateau',
    "Quaglino's",
    'Radici',
    'Sartoria',
    'Skylon',
    'South Place Chophouse',
    'The Modern Pantry',
]